In [1]:
import pandas as pd
import numpy as np

In [2]:
sales_data = np.array([
    [10, 20, np.nan, 40],
    [5,  np.nan, 15, 20],
    [30, 30, 30, 30],
    [np.nan, 5, 5, 5]
])

# Ціни на кожен з 4-х товарів
prices = np.array([100, 200, 50, 300])

In [25]:

mask = np.isnan(sales_data)
clean_data = np.where(mask, 0, sales_data)

In [4]:

prices = prices.reshape(4,1)# те саме що prices[:, np.newaxis]
clean_data * prices

array([[1000., 2000.,    0., 4000.],
       [1000.,    0., 3000., 4000.],
       [1500., 1500., 1500., 1500.],
       [   0., 1500., 1500., 1500.]])

In [5]:
col = ['Mon', 'Tue', 'Wed', 'Thu']
index = ['Apple', 'Banana', 'Orange', 'Grape']
df = pd.DataFrame(sales_data, index=index, columns=col)

In [6]:
df

         Mon   Tue   Wed   Thu
Apple   10.0  20.0   NaN  40.0
Banana   5.0   NaN  15.0  20.0
Orange  30.0  30.0  30.0  30.0
Grape    NaN   5.0   5.0   5.0

In [36]:
means = df.mean(axis=1)
print(means)
#Треба транспонувати бо за fillna йде по рядках
result = df.T.fillna(means).T
print(result)
final_res = df[df['Mon']>10]

Apple     23.333333
Banana    13.333333
Orange    30.000000
Grape      5.000000
dtype: float64
         Mon        Tue        Wed   Thu
Apple   10.0  20.000000  23.333333  40.0
Banana   5.0  13.333333  15.000000  20.0
Orange  30.0  30.000000  30.000000  30.0
Grape    5.0   5.000000   5.000000   5.0

In [8]:
# Таблиця з продажами за тиждень (вже почищена тобою)
# Використовуй свій df_filled з попереднього завдання

# Нова таблиця: Дані про постачальників
suppliers = pd.DataFrame({
    'info': ['FruitCo', 'GardenBest', 'FruitCo', 'EcoFarm'],
    'region': ['South', 'North', 'South', 'West']
}, index=['Apple', 'Banana', 'Orange', 'Grape'])

In [9]:
new_df = pd.concat([result, suppliers], axis=1)
new = new_df.groupby('region')['Mon'].sum()
new

region
North     5.0
South    40.0
West      5.0
Name: Mon, dtype: float64

In [46]:
region = suppliers['region']
arr_reg = np.array(region)
print(arr_reg)
mask = (arr_reg == 'South')
print(mask)
tax = np.where(arr_reg == 'South', 0.5, 0.1)
tax_col = tax.reshape(-1,1)
tax_col.shape
print(np.concat((result, tax_col),axis=1))#просто зєднує стовпці 
with_tax = result * tax_col
with_tax

['South' 'North' 'South' 'West']
[ True False  True False]
[[10.         20.         23.33333333 40.          0.5       ]
 [ 5.         13.33333333 15.         20.          0.1       ]
 [30.         30.         30.         30.          0.5       ]
 [ 5.          5.          5.          5.          0.1       ]]

         Mon        Tue        Wed   Thu
Apple    5.0  10.000000  11.666667  20.0
Banana   0.5   1.333333   1.500000   2.0
Orange  15.0  15.000000  15.000000  15.0
Grape    0.5   0.500000   0.500000   0.5

Аномалії

In [47]:
import pandas as pd
import numpy as np

df_dirty = pd.DataFrame({
    'product': [' apple', 'Apple ', 'APPLE', 'banana', ' Banana', 'ORANGE'],
    'sales': [10, 15, 10, 20, 25, 50]
})

In [80]:

df_dirty['product'] = df_dirty['product'].str.strip().str.lower()
df_clean = df_dirty
df_clean.groupby(df_clean['product']).sum()
df_clean['status'] = np.where(df_clean['sales'] > 30, 'High', 'Low')
df_clean

  product  sales status
0   apple     10    Low
1   apple     15    Low
2   apple     10    Low
3  banana     20    Low
4  banana     25    Low
5  orange     50   High

In [81]:
import pandas as pd
import numpy as np

# Дані про замовлення
orders = pd.DataFrame({
    'order_id': np.arange(100, 110),
    'quantity': [1, 5, 2, 10, 1, 8, 3, 4, 12, 2],
    'unit_price': [100, 50, 150, 40, 200, 30, 80, 90, 25, 110]
})

In [88]:
orders['totatal_cost'] = orders['quantity'] * orders['unit_price']
mean = orders['totatal_cost'].mean()
std = orders['totatal_cost'].std()
mask = (orders['totatal_cost'] > (mean+std))

In [89]:
orders['outliers'] = np.where(mask, True, False)

In [90]:
print(orders)

   order_id  quantity  unit_price  totatal_cost  outliers
0       100         1         100           100     False
1       101         5          50           250     False
2       102         2         150           300     False
3       103        10          40           400      True
4       104         1         200           200     False
5       105         8          30           240     False
6       106         3          80           240     False
7       107         4          90           360      True
8       108        12          25           300     False
9       109         2         110           220     False

In [95]:

labels = ['Cheap', 'Medium', 'Expensive']
orders['price_cat'] = pd.cut(orders['totatal_cost'], bins=3, labels=labels)
orders

   order_id  quantity  unit_price  totatal_cost  outliers  price_cat
0       100         1         100           100     False      Cheap
1       101         5          50           250     False     Medium
2       102         2         150           300     False     Medium
3       103        10          40           400      True  Expensive
4       104         1         200           200     False      Cheap
5       105         8          30           240     False     Medium
6       106         3          80           240     False     Medium
7       107         4          90           360      True  Expensive
8       108        12          25           300     False     Medium
9       109         2         110           220     False     Medium